site_name: YOLO-ONNX Documentation
site_url: https://niraj-ghetiya.github.io/mkdoc-test/
site_description: Documentation for YOLO-ONNX, a Python library for running YOLO models in ONNX format with Ultralytics.
site_author: Niraj Ghetiya

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/favicon.ico
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - toc.follow
    - header.autohide
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.button
    - content.footnotes
    - content.tooltips
    - content.code.annotate
    - content.code.select
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono

repo_url: https://github.com/niraj-ghetiya/mkdoc-test
repo_name: niraj-ghetiya/mkdoc-test
edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/niraj-ghetiya
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/niraj-ghetiya
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
  alternate:
    - name: English
      link: /
      lang: en
  giscus:
    repo: niraj-ghetiya/mkdoc-test
    repo_id: R_kgDOOgaRqg
    category: General
    category_id: DIC_kwDOOgaRqs4Cpg1K
    mapping: pathname
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: bottom
    theme:
      light: light
      dark: dark
    lang: en
  generator: false

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Usage:
      - Running Inference: usage/inference.md
      - Examples: usage/examples.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
  - License: license.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2
  - git-revision-date-localized
  - git-authors

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
