site_name: YOLO-ONNX Documentation
site_url: https://github.com/niraj-ghetiya/mkdoc-test
site_description: Documentation for YOLO-ONNX, a Python library for running YOLO models in ONNX format with Ultralytics.
site_author: Niraj Ghetiya

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share

repo_url: https://github.com/niraj-ghetiya/mkdoc-test
repo_name: niraj-ghetiya/mkdoc-test
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Usage:
      - Running Inference: usage/inference.md
      - Examples: usage/examples.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
  - License: license.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
