site_name: YOLO-ONNX Documentation
site_url: https://github.com/niraj-ghetiya/mkdoc-test
site_description: Documentation for YOLO-ONNX, a Python library for running YOLO models in ONNX format with Ultralytics.
site_author: Niraj Ghetiya

theme:
  name: material
  palette:
    primary: deep purple
    accent: amber
  features:
    - content.code.copy
    - content.tabs
    - navigation.sections
    - navigation.top
  logo: assets/logo.jpg  # Optional: Add a logo in docs/assets/logo.png
  favicon: assets/favicon.ico  # Optional: Add a favicon

repo_url: https://github.com/niraj-ghetiya/mkdoc-test
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - Usage:
      - Running Inference: usage/inference.md
      - Examples: usage/examples.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
  - License: license.md

plugins:
  - search
  - mkdocstrings:  # For generating API documentation from Python docstrings
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
