# .github/workflows/deploy-mkdocs.yml
name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', your default branch

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # If you are using Material theme or others
          pip install mkdocs-git-revision-date-plugin  # Example extra plugin

      - name: Build and Deploy
        run: |
          mkdocs gh-deploy --force
